### ISSUE TITLE
無法生成pdf

### ISSUE THREAD

**Issue by ChenChingChih** [liao961120/ntuthesis#17]
作者你好，
我在knit後遇到以下tex編譯的問題，不知道該怎麼解決...

> R version 4.0.1 (2020-06-06)
> TinyTex已經把所有tex套件都裝上

! Undefined control sequence.
<argument> \__xeCJK_patch_microtype_get_slot: 

���~: LaTeX failed to compile ntu-bookdown.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See ntu-bookdown.log for more info.
���~: Warning message:
In citation_package_arg(citation_package) :
  citation_package = 'none' was deprecated; please use 'default' instead.
�������

Exited with status 1.

謝謝你的幫忙!

**Comment by liao961120** [comment]
你的 tinytex 是 2020 版的嗎？
我不太確定原因，或許是 TexLive 2020 版本造成 xeCJK 出錯
所以可能要修改模板的中文字體部份 (將其註解掉)
或是使用舊版的 TinyTeX，例如，使用說明文件提供的連結 (https://doc-ntuthesis.netlify.app/install.html#latex)

或許可以參考下方的討論
https://d.cosx.org/d/421565-rmarkdown
https://d.cosx.org/d/421504-tinytexinstall-tinytex/12

**Comment by ChenChingChih** [comment]
我的tinytex 是 2020 版，剛剛裝好!
看來只能先試試看安裝舊版的...
先試試
`remotes::install_github('yihui/tinytex')
tinytex:::install_prebuilt()`
看看
感謝!

**Comment by ChenChingChih** [comment]
這個方法行不通...

**Comment by liao961120** [comment]
> 我的tinytex 是 2020 版，剛剛裝好!
> 看來只能先試試看安裝舊版的...
> 先試試
> `remotes::install_github('yihui/tinytex') tinytex:::install_prebuilt()`
> 看看
> 感謝!

這個方法只會安裝最新的 tinytex
你需要先移除你電腦上的tinytex (`uninstall_tinytex()`)
再按照ntuthesis說明文件上的方法，使用portable的tinytex
這樣才會使用舊版的

**Comment by ChenChingChih** [comment]
我載好舊版的tinytex，也試著跑ntuthesis，但是卡的有點久...
後來我先試Rmarkdown生成pdf，但是也跑不動...
```

---
title: "test"
author: "Chingchih"
date: "2020/5/5"
header-includes:
  - \usepackage{ctex}
output: 
  pdf_document: 
    latex_engine: xelatex
---
中文
englsih

```

再看到[最近bookdown升级了吗TeX中的定理环境重复](https://d.cosx.org/d/421590-bookdowntex)就覺得有點無解...

**Comment by ChenChingChih** [comment]
> 
> 
> > 我的tinytex 是 2020 版，剛剛裝好!
> > 看來只能先試試看安裝舊版的...
> > 先試試
> > `remotes::install_github('yihui/tinytex') tinytex:::install_prebuilt()`
> > 看看
> > 感謝!
> 
> 這個方法只會安裝最新的 tinytex
> 你需要先移除你電腦上的tinytex (`uninstall_tinytex()`)
> 再按照ntuthesis說明文件上的方法，使用portable的tinytex
> 這樣才會使用舊版的

**Comment by ChenChingChih** [comment]
```
---
title: "test"
author: "Chingchih"
date: "2020/5/5"
header-includes:
  - \usepackage{fontspec} # 使用 fontspec package
  - \usepackage{xeCJK}    # 使用 xeCJK package
  - \setCJKmainfont{標楷體} # 指定主要的字型，windows
output: 
  pdf_document: 
    latex_engine: xelatex
---
中文
englsih
```
這樣反而成功，應該是ctex出問題
